name: ci

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Windows Container
        uses: docker/build-push-action@v6
        with:
          platforms: windows/amd64
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:windows-latest
            ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Linux Container
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:linux-latest
            ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
